---

services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/nginx/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ${PWD}/nginx/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ${PWD}/nginx/var/log/nginx/
        target: /var/log/nginx/

  #
  # Fluent-Bit
  # Log収集ツール
  # Grafana/Promtail を利用していない理由:
  # - Fluent-BitにはLokiプラグインがデフォであるらしく、特別になにかDLする必要はない
  # - 実務でも利用している
  # - Fluentdは過去に触ってたので、ちょっとだけ知っている
  # シンプルな方はPromtailと評価されている記事をみたが、まずはFluent-Bitでいく
  # 辛くなったり、Promtailを利用してGrafanaで統一したくなったりしたら検討する
  #
  fluentbit:
    image: fluent/fluent-bit:3.1.9-debug
    ports:
      - "24224:24224"
    volumes:
      - type: bind
        source: ${PWD}/fluent-bit/etc/
        target: /fluent-bit/etc/
      - type: bind
        source: ${PWD}/nginx/var/log/nginx/
        target: /var/log/nginx/

  #
  # Loki(GrafanaのLGTMスタックのL)
  # Logのストレージと検索
  #
  loki:
    image: grafana/loki:3.2.1
    ports:
      - 3100:3100
    volumes:
      - type: bind
        source: ${PWD}/loki/loki/
        target: /loki/

  #
  # Grafana(GrafanaのLGTMスタックのG)
  # 可視化ツール
  #
  grafana:
    image: grafana/grafana:11.2.2
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ${PWD}/grafana/etc/grafana/provisioning/datasources/
        target: /etc/grafana/provisioning/datasources/
