---

services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/nginx/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ${PWD}/nginx/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ${PWD}/nginx/var/log/nginx/
        target: /var/log/nginx/
