---

services:
  nginx:
    image: nginx:1.27
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/nginx/etc/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ${PWD}/nginx/etc/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ${PWD}/nginx/var/log/nginx/
        target: /var/log/nginx/
  fluentbit:
    image: fluent/fluent-bit:3.1.9-debug
    ports:
      - "24224:24224"
    volumes:
      - type: bind
        source: ${PWD}/fluent-bit/etc/
        target: /fluent-bit/etc/
      - type: bind
        source: ${PWD}/nginx/var/log/nginx/
        target: /var/log/nginx/
  loki:
    image: grafana/loki:3.2.1
    ports:
      - 3100:3100
