apiVersion: 1

datasources:
  - name: Loki
    type: loki
    # access: proxy
    # アクセス方法の指定
    # proxy: GrafanaサーバーからLokiへのアクセス
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
